#!/usr/bin/env python3
"""Bundle modular Open WebUI pipe sources into single-file functions."""

from __future__ import annotations

import argparse
import ast
import hashlib
import py_compile
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_ROOT = ROOT / "src"
DIST_ROOT = ROOT / "dist"


@dataclass(frozen=True)
class Target:
    name: str
    entry_module: str
    output: Path


TARGETS: dict[str, Target] = {
    "responses": Target(
        name="responses",
        entry_module="owui_manifolds.providers.responses.pipe",
        output=DIST_ROOT / "responses.py",
    ),
    "gemini": Target(
        name="gemini",
        entry_module="owui_manifolds.providers.gemini.pipe",
        output=DIST_ROOT / "gemini.py",
    ),
    "anthropic": Target(
        name="anthropic",
        entry_module="owui_manifolds.providers.anthropic.pipe",
        output=DIST_ROOT / "anthropic_function.py",
    ),
}


def module_to_path(module: str) -> Path:
    path = SRC_ROOT.joinpath(*module.split(".")).with_suffix(".py")
    if path.exists():
        return path
    package_init = SRC_ROOT.joinpath(*module.split("."), "__init__.py")
    if package_init.exists():
        return package_init
    raise FileNotFoundError(f"Cannot resolve internal module {module!r}")


def source_for(module: str) -> str:
    return module_to_path(module).read_text(encoding="utf-8")


def internal_imports(tree: ast.Module) -> list[str]:
    modules: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom):
            if node.module and node.module.startswith("owui_manifolds."):
                modules.append(node.module)
        elif isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name.startswith("owui_manifolds."):
                    modules.append(alias.name)
    return modules


def dependency_order(entry_module: str) -> list[str]:
    order: list[str] = []
    seen: set[str] = set()

    def visit(module: str) -> None:
        if module in seen:
            return
        seen.add(module)
        tree = ast.parse(source_for(module), filename=str(module_to_path(module)))
        for dependency in internal_imports(tree):
            visit(dependency)
        order.append(module)

    visit(entry_module)
    return order


def module_docstring(source: str) -> str | None:
    tree = ast.parse(source)
    return ast.get_docstring(tree, clean=False)


def should_strip_node(node: ast.stmt, *, first_stmt: bool) -> bool:
    if first_stmt and isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant):
        return isinstance(node.value.value, str)
    if isinstance(node, ast.ImportFrom):
        if node.module == "__future__":
            return True
        return bool(node.module and node.module.startswith("owui_manifolds."))
    if isinstance(node, ast.Import):
        return any(alias.name.startswith("owui_manifolds.") for alias in node.names)
    return False


def stripped_source(module: str) -> str:
    source = source_for(module)
    tree = ast.parse(source, filename=str(module_to_path(module)))
    lines = source.splitlines()
    strip_lines: set[int] = set()
    for idx, node in enumerate(tree.body):
        if not should_strip_node(node, first_stmt=(idx == 0)):
            continue
        if node.lineno is None or node.end_lineno is None:
            continue
        strip_lines.update(range(node.lineno, node.end_lineno + 1))
    kept = [line for lineno, line in enumerate(lines, start=1) if lineno not in strip_lines]
    return "\n".join(kept).strip()


def build_target(target: Target) -> str:
    modules = dependency_order(target.entry_module)
    entry_docstring = module_docstring(source_for(target.entry_module)) or ""
    parts: list[str] = []
    if entry_docstring:
        parts.append('"""' + entry_docstring.replace('"""', r'\"\"\"') + '"""')
    parts.append("from __future__ import annotations")
    parts.append(
        "# NOTE: This file is generated by scripts/build_functions.py.\n"
        "# Edit src/owui_manifolds/ and rebuild; do not edit this file directly.\n"
        "# fmt: off"
    )
    for module in modules:
        body = stripped_source(module)
        if not body:
            continue
        rel = module_to_path(module).relative_to(SRC_ROOT)
        parts.append(f"# === {rel.as_posix()} ===\n{body}")
    return "\n\n".join(parts).rstrip() + "\n"


def validate_python(path: Path, source: str) -> None:
    ast.parse(source, filename=str(path))
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(source, encoding="utf-8")
    try:
        py_compile.compile(str(tmp), doraise=True)
    finally:
        tmp.unlink(missing_ok=True)
        pycache = tmp.parent / "__pycache__"
        if pycache.exists():
            for child in pycache.glob(tmp.name + "*"):
                child.unlink(missing_ok=True)


def write_if_changed(path: Path, source: str, *, check: bool) -> bool:
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == source:
        return False
    if check:
        old_hash = hashlib.sha256((existing or "").encode("utf-8")).hexdigest()[:12]
        new_hash = hashlib.sha256(source.encode("utf-8")).hexdigest()[:12]
        raise SystemExit(f"{path.relative_to(ROOT)} is stale ({old_hash} != {new_hash})")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(source, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="Build OWUI single-file functions")
    parser.add_argument("target", nargs="?", choices=sorted(TARGETS), help="Target to build")
    parser.add_argument("--check", action="store_true", help="Fail if dist files are stale")
    args = parser.parse_args()

    selected = [TARGETS[args.target]] if args.target else list(TARGETS.values())
    changed: list[Path] = []
    for target in selected:
        source = build_target(target)
        validate_python(target.output, source)
        if write_if_changed(target.output, source, check=args.check):
            changed.append(target.output)

    if args.check:
        print("dist files are up to date")
    elif changed:
        for path in changed:
            print(f"built {path.relative_to(ROOT)}")
    else:
        print("dist files already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
